language: generic
services:
  - docker

notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
    - ADDITIONAL_DEBS='apt-utils dialog curl wget'
    - CMAKE_ARGS=-DCMAKE_BUILD_TYPE=Release
    - NOT_TEST_DOWNSTREAM=true
    - ROS_REPO=ros
    - VERBOSE_OUTPUT=false
    - VERBOSE_TESTS=false
  matrix:
    - ROS_DISTRO=kinetic
    - ROS_DISTRO=melodic
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh
